### ISSUE TITLE
"Cannot open load file: subr-x": Does elm-mode actually require emacs 24.4?

### ISSUE THREAD

**Issue by helinko** [jcollard/elm-mode#103]
The above error comes when I try to activate elm-mode in emacs 24.3.1. According to 
[this](http://emacsredux.com/blog/2014/02/02/a-peek-at-emacs-24-dot-4-new-string-manipulation-functions/) it seems that the subr-x library ships with emacs 24.4-> but elm-mode's requirement for emacs is supposed to be just 24->, right? 

So do I have to upgrade my emacs to use elm-mode or am I missing something? 24.4. is not yet packaged for Ubuntu so I'd rather not upgrade.

**Comment by purcell** [comment]
A fix for this is included in my PR #104.
