### ISSUE TITLE
Elm-format is installed but reports can't be found

### ISSUE THREAD

**Issue by astoeckley** [jcollard/elm-mode#109]
I have elm-format.el and .elc in my .emacs dir for elm-mode-0.20.3.  When I try to use it in an Elm buffer, emacs reports "no such file or directory, elm-format".

elm-format-elm-version is set to 0.17.

Any idea what is happening here?

**Comment by purcell** [comment]
From your elm buffer, please use `M-:` to evaluate the following expressions, and post the results here:
- `(executable-find "elm-format")`
- `elm-format-command`

**Comment by purcell** [comment]
Also, `M-x toggle-debug-on-error` should turn this into an error which produces a stacktrace, which you could also paste here.

**Comment by astoeckley** [comment]
I found the problem, it was because I confused the elm-format emacs script with the elm-format command line tool. I had one of them, but not the other. Now it is working. Thanks.
