### ISSUE TITLE
proper tags support

### ISSUE THREAD

**Issue by nitingupta910** [jcollard/elm-mode#115]
Currently elm-mode uses ctags which is often not correct for jump-to-definition. Would you know if elm has a proper indexing tool which elm-mode can use to make it accurate?

**Comment by purcell** [comment]
I'm not aware of one, sorry. Generally jumping accurately to definitions of imported symbols is not trivial to do reliably.

**Comment by nitingupta910** [comment]
Ok, thanks for the info.
