### ISSUE TITLE
Backend company-elm doesn't work

### ISSUE THREAD

**Issue by welf** [jcollard/elm-mode#123]
For a long time, I used company autocompletion for my Elm files. But about 1,5 weeks ago it stopped working, although I didn't touch `company-mode` or `elm-mode` settings. 

When I type `upda` in Elm file containing a lot of functions which start with "update..." and then type `M-x company-complete` I get such error:
```
Debugger entered--Lisp error: (error "Company: backend company-elm async timeout with args (candidates upda)")
  signal(error ("Company: backend company-elm async timeout with args (candidates upda)"))
  error("Company: backend %s async timeout with args %s" company-elm (candidates "upda"))
  company--force-sync(company-call-backend-raw (candidates "upda") company-elm)
  company-call-backend(candidates "upda")
  company--fetch-candidates("upda")
  company-calculate-candidates("upda")
  company--begin-new()
  company--perform()
  company-auto-begin()
  company-manual-begin()
  company-complete()
  funcall-interactively(company-complete)
  call-interactively(company-complete record nil)
  command-execute(company-complete record)
  helm-M-x(nil "company-complete")
  funcall-interactively(helm-M-x nil "company-complete")
  call-interactively(helm-M-x nil nil)
  command-execute(helm-M-x)
```
In other major modes like `haskell-mode` or `emacs-lisp-mode` company completion works as expected, so it is a bug not in a `company`.

**Comment by purcell** [comment]
Thanks. This is related to #119: there should be a fix (and dramatic improvement) coming very soon - see #121 and #122.

**Comment by purcell** [comment]
In the meantime, #d4af45e should resolve this.
