### ISSUE TITLE
Autocomplete borken?

### ISSUE THREAD

**Issue by SekibOmazic** [jcollard/elm-mode#126]
Just tried fresh new install of elm-mode-20171111.2331 and got following warnings:

```
Warning (bytecomp): alist-get called with 5 arguments, but accepts only 2-4
Warning (bytecomp): ‘find-tag’ is an obsolete function (as of 25.1); use ‘xref-find-definitions’ instead.
Warning (bytecomp): the following functions are not known to be defined:
    haskell-ds-backward-decl, haskell-ds-forward-decl,
    inferior-haskell-flash-decl
```
The first one is the important one I guess. Reformatting elm files works fine, but autocomplete gives me:
```
Wrong number of arguments: (2 . 4), 5
eldoc error: (wrong-number-of-arguments (2 . 4)
```

**Comment by purcell** [comment]
Sorry about this -- we overhauled the completion recently, so it's much more awesome overall. The code _without_ @mattjbray's (now-applied) patch in #127 worked fine for me on a couple of machines, so I feel like maybe the patch will also break in some Emacs versions. I'll take a look in order to ensure it works everywhere.

**Comment by SekibOmazic** [comment]
@purcell Why sorry? You made a great software - big thanks for that. I forgot to say, I'm on Emacs v25.3.

**Comment by purcell** [comment]
In Emacs HEAD, which I'm using, we have the following:
```
(alist-get KEY ALIST &optional DEFAULT REMOVE TESTFN)
```
i.e. the arity is different. I've changed the code to use `assoc` instead now, which should work the same everywhere.

**Comment by purcell** [comment]
> Why sorry?

Because I'm always a bit sad if I break things for other people. :-)

Anyway, let me know if you encounter further problems.

**Comment by purcell** [comment]
P.S. I just fast-tracked an updated MELPA package containing the fix.

**Comment by SekibOmazic** [comment]
@purcell Uh, now I get this one:
```
Warning (bytecomp): assoc called with 3 arguments, but accepts only 2
```
And in Messages buffer:
```
Wrong number of arguments: assoc, 3
eldoc error: (wrong-number-of-arguments assoc 3)
```

**Comment by purcell** [comment]
Damn, that must also be different between Emacs versions! Will fix.

**Comment by purcell** [comment]
Done in a01626c, but I can't force a new package build from where I am now, sorry.

**Comment by SekibOmazic** [comment]
np, that can wait

**Comment by mattjbray** [comment]
Thanks @purcell! I did a quick Google for "emacs alist-get changelog" before submitting the patch but must admit I didn't look hard enough :)

**Comment by purcell** [comment]
These little changes API don't get documented terribly well, IMO. Anyway, hopefully it's all working for you now. :-)
