### ISSUE TITLE
How to turn off smart indentation?

### ISSUE THREAD

**Issue by quetz** [jcollard/elm-mode#129]
Using cycling based indentation is a real pain. It never does good thing and requires pressing tab at least once on every new line. 

I tried turning it off as described in #61 but it does not work. 
Also tried:
- `(turn-off-elm-indent)`
- `(elm-indent-mode nil)`

Is there any other way of disabling it? 
I settled on manually removing `elm-indent.el` file and all references to it but it is kinda harsh solution.

**Comment by purcell** [comment]
In recent versions, you should use the following, after `elm-mode.el` is loaded: `(remove-hook 'elm-mode-hook 'elm-indent-mode)`.

So put something like this in your start-up files:
```el
(with-eval-after-load 'elm-mode
  (remove-hook 'elm-mode-hook 'elm-indent-mode))
```

**Comment by quetz** [comment]
Somehow it does not work if used inside `dotspacemacs/user-init` or `dotspacemacs/user-config` but putting it at top level worked fine.

Thanks!
