### ISSUE TITLE
elm-package-latest-version: Symbol’s function definition is void: -find

### ISSUE THREAD

**Issue by spookylukey** [jcollard/elm-mode#131]
When I try to look up documentation for a function, after typing in the package name, I get this error:

    elm-package-latest-version: Symbol’s function definition is void: -find

I'm  using the latest elm-mode, and I get this error with GNU Emacs 24.5.1 and GNU Emacs 25.3.2.

**Comment by purcell** [comment]
You're missing the `dash` dependency, I believe, in which case installing from a package would have avoided this problem.

**Comment by spookylukey** [comment]
I installed elm-mode from MELPA using `package-install` - shouldn't that install dependencies automatically? In fact I did have dash installed, but it looks like an older version. I had to manually reinstall and now it works. I don't know how this could have happened.

**Comment by purcell** [comment]
Aha. We wouldn't have specified as a dependency the specific Dash version that introduced `-find`: we'd just have used the latest stable release version. If you're going to use MELPA, it's recommended practice to routinely update packages.
