### ISSUE TITLE
Only matching against .localName now?

### ISSUE THREAD

**Issue by c50a326** [jcollard/elm-mode#136]
Hi

https://github.com/jcollard/elm-mode/commit/6f3f22873cee788d7b458581521441b5757bdaa3?diff=split#diff-c3633a01c792e88846f0ecf0214a49e0L909

I see that these changes mean that if I import like `import Html exposing (..)` and then have `Html.program` in my code, I won't be able to `elm-oracle-type-at-point` or `elm-oracle-doc-at-point`, whereas without this change (keeping the `or` logic for matching against both `.localName` and `.fullName`) then it's no problem.

Is there a reason to not do this?

As an aside, do you know why I can't use elm-oracle on Elm's main `main`? Just curious.

**Comment by purcell** [comment]
Yeah, the expectation was that if you want to use qualified symbols, you'd simply use `import Html`. But I agree it would be nice if this worked anyway. I *think* the fault is not *exactly* the commit in question, which was part of rewriting the completion system, but rather the catalog of candidates needs to be built a little differently. I'll look at this if I get chance.

**Comment by purcell** [comment]
Closing as "won't fix" since we're moving away from the defunct `elm-oracle` for hand-rolled completion in favour of recommending the ELM LSP server.
