### ISSUE TITLE
repl does not load after upgrading to elm 0.19

### ISSUE THREAD

**Issue by mattsawyer77** [jcollard/elm-mode#138]
running `elm-repl` results in the following error message:

```
apply: Searching for program: No such file or directory, elm-repl
```

From my shell I can execute `elm repl` but not `elm-repl`.

**Comment by Fedreg** [comment]
@mattsawyer77 elm commands are now `elm` plus the verb... so elm-make is now `elm` `make` and elm-repl in now `elm repl`. You can change some of the commands in your local copy of elm-mode. in the `elm-interactive.el` file until someone updates this package.  I don't know enough about the code to offer a PR myself.

**Comment by purcell** [comment]
Does https://github.com/jcollard/elm-mode/pull/139 help?

**Comment by mattsawyer77** [comment]
@purcell thanks but that didn't work for me -- I left a comment on the PR.

@Fedreg I tried changing the command in elm-interactive.el to `elm repl` but that didn't work either:
```
apply: Searching for program: No such file or directory, elm repl
```
I did verify that `!which elm` does return `/usr/local/bin/elm`.

**Comment by purcell** [comment]
#139 is merged now, but I'll keep this issue open for visibility until Elm 0.19 support is more established. In the meantime, it should be sufficient to create a `.dir-locals.el` in the `src` dir or root of an Elm 0.19 project containing something like the following:

```
((elm-mode
  (elm-interactive-command . ("elm" "repl"))
  (elm-reactor-command . ("elm" "reactor"))
  (elm-reactor-arguments . ("--port" "8000"))
  (elm-compile-command . ("elm" "make"))
  (elm-compile-arguments . ("--output=elm.js" "--debug"))
  (elm-package-command . ("elm" "package"))
  (elm-package-json . "elm.json")))
```

**Comment by mattsawyer77** [comment]
@purcell got the latest elm-mode just now. and the .dir-locals.el snippet works great. thanks!

hopefully elm-mode can work out-of-the-box with 0.19 at some point.

**Comment by purcell** [comment]
@mattsawyer77 Excellent, thanks for confirming that.

Yes, I'd like to make everything work out of the box, if only to minimise support load here. :-)

I've also been looking at fixing up `flycheck-elm`, but it looks like there have been big changes in the json output of `elm make`, so that's a bigger job, sadly.

**Comment by caw** [comment]
Fantastic - works for me too - really appreciate that tip.
Should I not expect company to work until elm-oracle is updated?
thanks again

**Comment by purcell** [comment]
> Should I not expect company to work until elm-oracle is updated?

Pretty much, yep. I think the community as a whole will take a little while to get all the tools updated.

**Comment by purcell** [comment]
Closing this now -- I've opened #141 to cover better detection of Elm versions and corresponding auto-configuration.
