### ISSUE TITLE
Auto-configure when projects use Elm 0.19 vs 0.18

### ISSUE THREAD

**Issue by purcell** [jcollard/elm-mode#141]
As detailed in https://github.com/jcollard/elm-mode/issues/138#issuecomment-416761616, it's now largely possible to configure `elm-mode` for Elm 0.19 projects, but it would probably be better if this were auto-detected. In fact, the presence of `elm.json` vs `elm-package.json` should be enough of a clue in most cases.

(Noting this here for future implementation by myself or another contributor.)

**Comment by saurabhnanda** [comment]
I've spent the last 2-3 hours trying to get elm-mode working with my 0.19 project properly, but haven't been successful. Here's what I tried:

- Upgraded spacemacs packages to get the latest version of elm-mode and flycheck-elm
- Tried customising the following variables in `~/.spacemacs` file, as well as `.dir-locals.el` as mentioned at https://github.com/jcollard/elm-mode/issues/138#issuecomment-416761616
  - `elm-compile-command`
  - `elm-interactive-command`
  - `elm-package-command`
  - `elm-reactor-command`
- Tried setting the command/s to absolute paths, eg. `<home-dir>/.nvm/versions/node/v10.4.0/bin/elm`
- Tried setting my default NVM to 10.4.0 (it was 6.11.1 earlier). Confirmed that a new bash / terminal is using nvm 10.4.0

```
        v6.11.1
         v8.2.1
->      v10.4.0
         system
default -> v10.4.0
node -> stable (-> v10.4.0) (default)
stable -> 10.4 (-> v10.4.0) (default)
iojs -> N/A (default)
lts/* -> lts/carbon (-> N/A)
lts/argon -> v4.9.1 (-> N/A)
lts/boron -> v6.14.2 (-> N/A)
lts/carbon -> v8.11.2 (-> N/A)
```

- Tried uninstalling 0.18 via `npm uninstall elm@0.18`
- Tried physically removing the `elm-make`, `elm-package`, `elm-repl` and `elm-reactor` from `~/.nvm/versions/node/v10.4.0/bin`

Nothing worked. My brain is fried.

Any help would be appreciated.

**Comment by purcell** [comment]
Please can you be more specific than "nothing worked"? What steps did you follow, what did you expect, and what happened instead?

**Comment by danieljaouen** [comment]
Should we expect `company-elm` to not work until this is resolved?

**Comment by purcell** [comment]
> Should we expect `company-elm` to not work until this is resolved?

Yes, correct. See https://github.com/jcollard/elm-mode/issues/142 for the completion-specific side of things. It's not pretty.

**Comment by danieljaouen** [comment]
I don't know if you get this often or not, but I just wanted to thank you for your hard work and dedication for working on this project.  The whole `elm-oracle` debacle looks like a mess and I am super glad that there is someone on the other side of things willing to tackle problems like these.  :-)

**Comment by purcell** [comment]
Thanks, I appreciate it, but I should also caution that I haven't concretely tackled it yet. :-) It was frustrating to get `elm-oracle` completion working so nicely with 0.18 only to have it break.

**Comment by danieljaouen** [comment]
Nevertheless, it is a noble effort.  I don't have much in the way of finances to remunerate you for your hard work, but I figured a word of encouragement wouldn't hurt.  :-)

**Comment by purcell** [comment]
The 0.19 config is now the default. I no longer plan to pursue auto-configuration for older Elm versions.
