### ISSUE TITLE
(0.19) Elm reactor does not recognize flag `-p`

### ISSUE THREAD

**Issue by benreyn** [jcollard/elm-mode#144]
When running `elm reactor` in elm 0.19 the `*elm-reactor*` buffer displays this message...

```
I do not recognize this flag:

    [91m-p[0m

Maybe you want [92m--port=<port>[0m instead?


Process elm-reactor exited abnormally with code 1
```

Apparently in elm 0.19 the `-p` flag is deprecated and now expects the command to be run as. `elm reactor --port=8080` it also appears as though the `-a` flag is now deprecated. I was going to just submit a patch but given that there are alot of changes floating around regarding elm 0.19 and #141 is open, I figured I would open an issue to discuss fist.

**Comment by purcell** [comment]
Yeah, as noted [here](https://github.com/jcollard/elm-mode/issues/138#issuecomment-416761616) I think this problem can currently be configured away, and #141 would cover the auto-configuration (or updated defaults) for this later.

**Comment by benreyn** [comment]
Oh, I see! I need to set `elm-reactor-arguments` as well! Thanks @purcell !
