### ISSUE TITLE
How to resolve eldoc error

### ISSUE THREAD

**Issue by nikolaipaul** [jcollard/elm-mode#145]
I'm fairly new to emacs and I can't get elm-mode to work as expected.

Things that don't work:
- Autocompletion
- Showing errors
- Showing types of expressions

I installed elm via the nix package manager. All the elm commands do work in the terminal.

Can you help me to resolve that issue? 

This is the error I receive:

<img width="481" alt="bildschirmfoto 2018-10-31 um 16 14 37" src="https://user-images.githubusercontent.com/25384717/47798180-1d9c1a00-dd28-11e8-8241-39d5979f352e.png">

**Comment by purcell** [comment]
Please see #141 and #142. The latter talks about how eldoc and completion don't yet work with Elm 0.19 (because we rely on `elm-oracle`, which isn't compatible with 0.19). The former gives some tips on how to generally configure `elm-mode` for Elm 0.19, which must be done manually for now.
