### ISSUE TITLE
type annotations for Elm 0.19

### ISSUE THREAD

**Issue by johbra** [jcollard/elm-mode#152]
If I type C-c C-a I get a message like
Wrote /var/folders/r8/mm42spk12vbg3j856x5hr5qr0000gn/T/elm-comp-in-59859mMk.elm
But no type annotations are added to the .elm buffer

**Comment by purcell** [comment]
I'll confess to being quite frustrated by all the breakage introduced by Elm 0.19, and I don't currently have much faith that it will be addressed upstream.

**Comment by johbra** [comment]
It's a pity, I regret your frustration. But for me, a programming language without an effective Emacs mode isn't worth to be used further.

**Comment by purcell** [comment]
> It's a pity, I regret your frustration. But for me, a programming language without an effective Emacs mode isn't worth to be used further.

It's a chicken and egg thing for me: my motivation to work on Emacs modes like this is related to my trust in the language. :-)

**Comment by johbra** [comment]
> It's a chicken and egg thing for me: my motivation to work on Emacs modes like this is related to my trust in the language. :-)

Indeed, that's a problem. I am teaching functional programming (using Racket, Clojure/Clojurescript) and I am trying to figure out, if Elm could be an alternative. But especially for beginners you need a good support by editors or IDEs.

**Comment by johbra** [comment]
Thanks for the hints, but for now I'll not give up using Elm

**Comment by purcell** [comment]
Yep, definitely not trying to talk you out of it. :-)

**Comment by theothornhill** [comment]
Is this still relevant?

**Comment by purcell** [comment]
I suspect (but have not checked) that `elm-make` hasn't grown a `--warn` flag, so I think there's no route for fixing this. Does LSP support inserting type signatures?

**Comment by theothornhill** [comment]
Yeah, `elm-language-server` can infer and insert types now:

![image](https://user-images.githubusercontent.com/26711805/109283532-2e3cfc00-781f-11eb-871a-c4386cc48c83.png)

![image](https://user-images.githubusercontent.com/26711805/109283582-3e54db80-781f-11eb-872b-7e079708936c.png)

**Comment by purcell** [comment]
Great, then fixing this will be out of scope for elm-mode, given current lack of core tool support.
