### ISSUE TITLE
Corrupted file after elm-format-on-save

### ISSUE THREAD

**Issue by rofrol** [jcollard/elm-mode#156]
Last good commit for me is 57104f0d7e98bfa6aeaec5854d933291d19aedb4.

This:

```elm
module Mapdid.App exposing (main)

import Animation
import Browser
import Browser.Dom
import Browser.Events
import Browser.Navigation as Nav
import Element exposing (Element)
import Element.Background
import Element.Border
```

formats to this:

```elm
module Mapdid.App exposing (maimn)

import Animation
import Browser
import Browser.Dom
import Brr
iopowser.EvenrtDs

import tr Bserrovwnts
impser.Navigation as Nav
import
iElement emxptosing (Element)
import Element.Background
import orElement.B.orrder
```

This is my config https://github.com/rofrol/.emacs.d/blob/df81ad4c5958072fda5cf413b8838b6a2482cef0/lisp/rofrol-elm.el

**Comment by rofrol** [comment]
Looks like this works https://github.com/jcollard/elm-mode/commit/dc5ce009b18c07e5235d1974691b372fc0cacace

But not autoformat with saving but manually running `elm-mode-format-buffer`.

**Comment by rofrol** [comment]
Also I am using this for formatting on save:

`(add-hook 'before-save-hook #'elm-mode-format-buffer)`

**Comment by purcell** [comment]
Hmm. Are you on Emacs 26.1? And which version of the `reformatter` package do you have?

**Comment by purcell** [comment]
BTW your config is quite broken. You add an `after-save-hooks` function at the top level but you pass the "local" flag, so you're still modifying the global version of `after-save-hooks`. What you instead want is to add that hook locally inside the elm-mode buffer, e.g. in a function added to `elm-mode-hook`. (You can then safely skip checking whether `major-mode` is `elm-mode`... and in any case, prefer `derived-mode-p` to `(eq major-mode ...)`)

**Comment by purcell** [comment]
My guess at what's happening here is that you have an old snapshot version of Emacs which nonetheless looks newer than 26.1, and is getting hit by the emacs version check [here](https://github.com/purcell/reformatter.el/blob/master/reformatter.el#L215), so that your reformatting is messed up by the core `replace-buffer-contents` function being broken.

**Comment by purcell** [comment]
> old snapshot version of Emacs which nonetheless looks newer than 26.1,

In case this is the problem, I've pushed a fix in https://github.com/purcell/reformatter.el/commit/0da7241ca20df4d3e5f4ccbd03227816d8d5f698.

**Comment by rofrol** [comment]
I am using remacs.

```
$ emacs --version
GNU Emacs 27.0.50
Copyright (C) 2018 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
```

**Comment by rofrol** [comment]
Works after fix.

**Comment by purcell** [comment]
> I am using remacs.

Then that version of remacs must have the bug that was subsequently fixed in Emacs.

> Works after fix.

Cool, thanks for confirming.
