### ISSUE TITLE
Add Debug mode which uses elm-reactor

### ISSUE THREAD

**Issue by jcollard** [jcollard/elm-mode#16]

**Comment by Bogdanp** [comment]
@jcollard what do you think this should look like? Do you think `C-c C-m` as it is right now is sufficient or should we add a prefix version `C-u C-c C-m` that appends `?debug` to the URL?

**Comment by jcollard** [comment]
Either should be fine. I would prefer the non-prefix version.

**Comment by jcollard** [comment]
Just looked at the bindings and the prefix seems better to me actually.

**Comment by jcollard** [comment]
Thanks again!
