### ISSUE TITLE
Requires reformatter.el?

### ISSUE THREAD

**Issue by kraai** [jcollard/elm-mode#161]
When I tried to install `elm-mode` manually and open a file, Emacs displayed the following error:

```
File mode specification error: (file-missing Cannot open load file No such file or directory reformatter)
```

Once I installed [reformatter.el](https://github.com/purcell/reformatter.el), this error went away.  Is this the correct way to resolve this error?  If so, should `reformatter.el` be added to the list of dependencies?

**Comment by purcell** [comment]
Yes, it's already [in the list of dependencies](https://github.com/jcollard/elm-mode/blob/master/elm-mode.el#L7).

**Comment by purcell** [comment]
I see there was an incorrect explicit list of deps in the README which may have confused matters, so I've removed that now. Thanks!

**Comment by kraai** [comment]
Thanks!  I should have mentioned that I was using the list in `README.md`.

**Comment by purcell** [comment]
All good. Happy New Year!
