### ISSUE TITLE
Types of items for imenu should be optional.

### ISSUE THREAD

**Issue by akoppela** [jcollard/elm-mode#162]
Recently `elm-imenu.el` was changed with types of items addition. I like previous behavior much more. I always know what I want to look for and I never want to search a specific function or type, etc. Does that make sense to make types of items an optional thing? I may submit a patch if required.

**Comment by purcell** [comment]
Done, set `elm-imenu-use-categories` to `nil` to get the old behaviour.

**Comment by akoppela** [comment]
Thank you sir.

**Comment by purcell** [comment]
Happy to help
