### ISSUE TITLE
package install failed: 

### ISSUE THREAD

**Issue by ireneo-funes** [jcollard/elm-mode#172]
![Screen Shot 2020-08-13 at 2 52 13 PM](https://user-images.githubusercontent.com/39878205/90099100-ae64ae00-dd74-11ea-8a1a-21816ba65c9c.png)

When I tried to run package install elm-mode, I got this error.
>https://stable.melpa.org/packages/reformatter-0.4.el: Not found

Is there anything I'm missing for this installation?

p.s. I ran GNU emacs 26.3 on Mac OS X Catalina version 10.15.6

**Comment by purcell** [comment]
Probably need to refresh your package list because 0.5 is the current version: https://stable.melpa.org/#/reformatter. PS. you can simplify your "Use melpa" snippet above too, now that we only support "https". Check out the example in the README.

**Comment by ireneo-funes** [comment]
Thanks, @purcell. After running `M-x package-refresh-contents`, I can successfully install this package.
