### ISSUE TITLE
Indent tab cycling not working as expected for me

### ISSUE THREAD

**Issue by thepreacher** [jcollard/elm-mode#174]
> elm-mode indentation is based on cycling: every time you insert a new line there will be one or more indentation levels available for you to choose from. The exact number is printed in the minibuffer either as Sole indentation or Indent cycle (n)... where n is the number of available indentations to choose from. If the automatic indentation level was not the one you expected simply hit TAB to cycle through the list (note that hitting any other key will cancel the cycle).

I'm using *doom emacs* and I have zero additional `elm` config in my `config.el` file. According to the above, what I expect is, when I enter a new line and the *indent cycle (n)* shows in the status line (and without touching any key prior), I can hit the TAB key to cycle through to find the right indent level for my purpose.

However, what happens for me is, when I hit TAB first time, nothing happens i.e. cursor doesn't move. Then subsequent TABs just keep moving the cursor along without cycling.

**Comment by purcell** [comment]
Please post what command `TAB` is bound to in that buffer: `C-h k TAB` should tell you this.

**Comment by thepreacher** [comment]
Ah! it's bound to `better-jumper-jump-forward`. Never even heard of that before. How do I overwrite that behaviour?

**Comment by purcell** [comment]
That's a bit out of scope for discussion here, sorry, I'm not familiar with Spacemacs' config: best to ask there.
