### ISSUE TITLE
Remove reliance on reformatter

### ISSUE THREAD

**Issue by theothornhill** [jcollard/elm-mode#178]
Hi again!

I'm wondering - making the assumption that most elm/emacs users are using an lsp-client - maybe it is time to remove the reformatter code? I know the package is yours, but it feels like installing packages when the same functionality is supplied by the de facto tooling shouldn't be necessary. 

I also know it is working code, and as such may break some users workflow, but likely they already have installed the alternative already. 

I'm putting this up for discussion before making a PR to get your opinion on this. What do you think?

**Comment by purcell** [comment]
Nope, leaving it for now, thanks. It's reasonable to provide basic integration with core community tools.

**Comment by purcell** [comment]
> as such may break some users workflow

(I am one such user. 😄 )

**Comment by coddeys** [comment]
I am one such user too. smile
