### ISSUE TITLE
#22 causes spurious repetition of function name

### ISSUE THREAD

**Issue by conklech** [jcollard/elm-mode#23]
Consider this state:

    f x = 
         ^

where `^` indicates cursor position. Starting a new line results in this state:

    f x =
    f 
      ^

which is never correct. Furthermore, using tab to cycle through tab stops does not remove `f`, as it did before #22 if you tabbed through this option.

**Comment by jcollard** [comment]
Reverted #22 here #24 .

**Comment by conklech** [comment]
The problem #22 was intended to resolve should be fixed though.
