### ISSUE TITLE
elm-mode requires let-alist 1.0.7, but only 1.0.4 available

### ISSUE THREAD

**Issue by wilhelmson** [jcollard/elm-mode#28]
I tried installing elm-mode this evening, and I received an error that ```let-alist-1.0.7``` was required, but only ```1.0.4``` was found. I hit [GNU ELPA](http://elpa.gnu.org/packages/let-alist.html) and it looks like ```1.0.4``` is the latest available.

**Comment by jcollard** [comment]
Is this fixed with the latest PR from @Bogdanp ?

**Comment by Bogdanp** [comment]
@jcollard Yup, I just did a `(package-refresh-contents)` followed by `M-x package-install RET elm-mode RET` and everything installed cleanly :)

**Comment by jcollard** [comment]
Awesome! Thanks!

**Comment by wilhelmson** [comment]
Thank you!
