### ISSUE TITLE
Compiling buffer with --output filename

### ISSUE THREAD

**Issue by usharf** [jcollard/elm-mode#32]
I can see that the interactive functions support passing an OUTPUT file name for compilation, but not sure how to use it. Coming a buffer always yields "elm.js" rather than "<buffer/file-name>.js"...

**Comment by Bogdanp** [comment]
This will be coming in a future release but isn't yet exposed in a nice way. To work around it you could temporarily write your own interactive function that wraps one of the compilation functions for example:

```elisp

(defun my-elm-compile-buffer (output)
  (interactive "F")
  (elm-compile--file (elm--buffer-local-file-name) output))
```

**Comment by usharf** [comment]
Thanks. I'll do that.
