### ISSUE TITLE
Setting flags for the repl

### ISSUE THREAD

**Issue by usharf** [jcollard/elm-mode#33]
Is there a way to automatically pass certain flags to the repl? i.e. When the file loaded into the repl is in a subdirectory, have the repl activated with `:flags add --src-dir=src` or something like this.

PS I'm not able to do this even manually right no (elm make complains when trying to import any module after altering `--src-dir` in this way, so I guess I'm missing something...

**Comment by Bogdanp** [comment]
It's certainly something you _can_ do if you're willing to write your own load function. Check out the implementation of `load-elm-repl` in `elm-interactive.el`  and `elm-interactive--send-command` in the same file. However, if all you want is for the REPL to respect your source directory settings then `elm-mode` should have you covered. Just make sure you have 

```json
    "source-directories": [
        "src"
    ],
```

in your `elm-package.json` file and everything should work as expected. `elm-repl` bases its load path on that file and `elm-mode` always tries to run commands with the working directory set to the folder that `elm-package.json` resides in.

Regarding not being able to do it manually: make sure your `elm-package.json` lives outside of your `src` folder. When `elm-mode` searches for that file it starts in the current directory of the current source file and works its way up the tree until it finds it.

**Comment by usharf** [comment]
I guess sticking the configuration in one place is actually my preferred way of doing this (considering other parts of the workflow might need the same configuration), which works with `elm-mode` like you've suggested, so that's great.
