### ISSUE TITLE
Configuration layer for spacemacs

### ISSUE THREAD

**Issue by ayoshi** [jcollard/elm-mode#35]
Hi.

Thank you for you work on elm-mode!

Would you be willing to contribute a properly configured layer for Spacemacs? 
http://spacemacs.org/
https://github.com/syl20bnr/spacemacs
It is probably the most widely used configuration for Emacs now.

**Comment by jcollard** [comment]
Currently, I have no intent to develop a layer for Spacemacs. Unfortunately, I do not have the time to do this. If someone were to do this, I would be more than happy to assist in integration.
