### ISSUE TITLE
elm-oracle doesn't work with elm-mode (Windows)

### ISSUE THREAD

**Issue by TheCrafter** [jcollard/elm-mode#36]
Hello,

I am using `Windows 8.1 x64`, my emacs version is `24.5.1` and I have the latest `Elm` and `elm-mode` versions. I am trying to configure elm-mode on emacs. So far everything seems to work fine.

Except that "elm-oracle" part. I cannot get it to work.

I installed `elm-oracle` and then I tried adding `(add-hook 'elm-mode-hook #'elm-oracle-setup-completion)` or `(add-hook 'elm-mode-hook #'elm-oracle-setup-ac)` on my `.emacs` file but I just cannot get it to work.

Am I missing something or there is an actual problem here?

**Comment by Bogdanp** [comment]
Make sure `elm-oracle` is in your `PATH` and that Emacs shares that `PATH`. You should be able to do something like `M-x shell-command RET elm-oracle RET` to check.

I don't have a Windows machine so I can't debug this myself. Does a particular error get raised? Have you tried running it with debug-on-error mode on (`M-x toggle-debug-on-error RET`)?

**Comment by TheCrafter** [comment]
`elm-oracle` is on  my `PATH`. But I tried running it with debug-on-error mode. So when I tried to open an elm file for the first time the `Backtrace` buffer appeared with this:
```
Debugger entered--Lisp error: (void-variable elm)
  elm-oracle-setup-ac()
  run-hooks(change-major-mode-after-body-hook prog-mode-hook elm-mode-hook)
  apply(run-hooks (change-major-mode-after-body-hook prog-mode-hook elm-mode-hook))
  run-mode-hooks(elm-mode-hook)
  elm-mode()
  set-auto-mode-0(elm-mode nil)
  set-auto-mode()
  normal-mode(t)
  after-find-file(nil t)
  find-file-noselect-1(#<buffer Main.elm> "d:/Code/Elm/Projects/Test/Main.elm" nil nil "d:/Code/Elm/Projects/Test/Main.elm" ((7936 0 . 2333) (22581 . 33668)))
  find-file-noselect("d:/Code/Elm/Projects/Test/Main.elm" nil nil t)
  find-file("d:/Code/Elm/Projects/Test/Main.elm" t)
  call-interactively(find-file nil nil)
  command-execute(find-file)
```

**Comment by Bogdanp** [comment]
@TheCrafter what version of `auto-complete` do you have installed? Could you try upgrading to the latest version on melpa?

The only reference to `elm` in `elm-oracle-setup-ac` is inside the definition macro:

```lisp
    (ac-define-source elm
      `((candidates . (elm-oracle-get-completions ac-prefix))
        (prefix . ,elm-oracle--pattern)
        (document . elm-oracle-get-documentation)))
```

And that _should_ be a valid invocation of the macro given a recent version of `auto-complete`.

**Comment by TheCrafter** [comment]
@Bogdanp I've just installed auto-complete from melpa. So it is the latest. Can you recreate the problem on Windows? Or is it only me?

**Comment by Bogdanp** [comment]
@TheCrafter I don't have a Windows machine to test on. What's the output of evaluating `ac-version`? If it is `1.5.0` then it's probably something else in your config that's breaking things.

You could try running emacs with the bare-minimum config required to run `elm-mode` and `auto-complete` by running an adapted version of the following command:

```bash
emacs -Q \
  -L .emacs.d/elpa/f-20150605.927/ \
  -L .emacs.d/elpa/s-20150909.608/ \
  -L .emacs.d/elpa/dash-20150829.433/ \
  -L .emacs.d/elpa/let-alist-1.0.4/ \
  -L .emacs.d/elpa/auto-complete-20150618.1949/ \
  -L .emacs.d/elpa/popup-20150626.711/ \
  -L .emacs.d/vendor/elm-mode/ \
  --eval "(require 'auto-complete)" \
  --eval "(require 'auto-complete-config)" \
  --eval "(require 'elm-mode)" \
  --eval "(ac-config-default)" \
  --eval "(ac-set-trigger-key \"TAB\")" \
  --eval "(add-hook 'prog-mode-hook #'auto-complete-mode)" \
  --eval "(add-hook 'elm-mode-hook #'elm-oracle-setup-ac)"
```

You're probably going to have to update those `-L` paths but that should at least tell us if there's something in your config that's interfering with `elm-mode` or if it really is something OS-related.

**Comment by whitehead1415** [comment]
I am running arch linux and I'm getting the same error as @TheCrafter 

@Bogdanp I have the latest version of auto-complete and ac-version says it's 1.5.0
I tried using that bare minimum config. Even running with that config gives me the same error.

So it doesn't seem to be a config or an OS  issue.

**Comment by TheCrafter** [comment]
@Bogdanp I also have the latest auto-complete version (1.5.0) with the bare minimum configuration.

**Comment by Bogdanp** [comment]
@whitehead1415 @TheCrafter please try the latest version (an update should be pushed to melpa within the next couple of hours) and let me know if it works.

**Comment by whitehead1415** [comment]
Thanks that fixed it :)

**Comment by Bogdanp** [comment]
Alright, I'm closing this one for now.
