### ISSUE TITLE
No keybinding to stop elm reactor

### ISSUE THREAD

**Issue by lethjakman** [jcollard/elm-mode#40]
The elm bindings are great to start up an elm reactor and navigate to it in a browser, but I'm having issues once I'm navigating to new projects. I'm finding that I have to manually kill the process otherwise it will continue to open the previously opened project. Perhaps I missing something how to kill the proccess or something?

**Comment by lethjakman** [comment]
The issue was on my side as far as opening a new project goes, my apologies. It does open a new session version and close the old one. However I still can't figure out how to close the old one without opening a task manager of sorts.

**Comment by Bogdanp** [comment]
Right now you need to kill the `*elm-reactor*` buffer and its associated process but I can see how that can get annoying. I don't think there's any reason why `run-elm-reactor` couldn't do that for you automatically so I'll try to add that in sometime next week.

**Comment by lethjakman** [comment]
Fantastic, thank you for your help!
