### ISSUE TITLE
Melpa stable

### ISSUE THREAD

**Issue by Skinney** [jcollard/elm-mode#42]
Would be nice to have this on melpa stable

**Comment by Skinney** [comment]
@jcollard any thoughts on this? I think it's just a matter of adding a git tag for the library to be added to melpa stable.

**Comment by Bogdanp** [comment]
It's hard to have a "stable" package against an unstable language. That is, many backwards-incompatible changes in Elm itself will likely lead to backwards-incompatible changes to `elm-mode`. If we were to follow semantic versioning we could pick an arbitrary starting point like `0.x.y` to represent the fact that the API may change at any time until Elm itself has a stable release but I feel like that would sort of defeat the point of the whole thing. Would a scheme like that still be useful to you as a MELPA stable user?

**Comment by Skinney** [comment]
Yes. It allows me to use Melpa for all my packages. Besides, Elm doesn’t update all that often, and elm-mode is pretty stable in my experience.

**Comment by Bogdanp** [comment]
Alright, I've tagged the current `HEAD` as `v0.5.0` (as an arbitrary starting point). Let me know if you encounter any issues.

**Comment by Skinney** [comment]
Thanks!
