### ISSUE TITLE
install from source broken link?

### ISSUE THREAD

**Issue by davidsiefert** [jcollard/elm-mode#46]
This is listed as a requirement for installing from source:
* https://github.com/Malabarba/let-alist

Currently 404s.  Still a requirement? new repo? help?

**Comment by Bogdanp** [comment]
Can you give the ELPA version a try and let me know how it goes? 

https://elpa.gnu.org/packages/let-alist.html

**Comment by Bogdanp** [comment]
I've updated the link in the README. Thanks for reporting this!
