### ISSUE TITLE
Identifiers with primes in them are colored incorrectly

### ISSUE THREAD

**Issue by porglezomp** [jcollard/elm-mode#53]
At the top level, writing
```elm
foo = 1
foo' = 2
```
`foo` is colored, and the `foo` in `foo'` is also colored, but the `'` is not. Identifiers like `foo'` and `foo'bar'` should all be colored correctly.

Similarly, `type'` has `type` highlighted as a keyword and then the `'` colored as normal text, when `type'` is a normal identifier.

**Comment by Bogdanp** [comment]
Thanks for reporting! This issue should now be fixed.

**Comment by porglezomp** [comment]
Thanks, looks great over here.
