### ISSUE TITLE
elm-format dumps into the buffer

### ISSUE THREAD

**Issue by porglezomp** [jcollard/elm-mode#54]
Running elm-format on a buffer which hasn't been saved yet spits the following
```
Could not find any .elm files on the specified paths:

    /home/caleb/dumb.elm

Please check the given paths.
```
out at your cursor.
Similarly, formatting a file with a syntax error places
```
Processing file /home/caleb/dumb.elm
ERRORS
```
at your cursor.

To reproduce, create a new empty file `test.elm` and then hit `C-c C-f`.
Also, save the file and hit `C-c C-f`.

**Comment by Bogdanp** [comment]
This should now be fixed, thanks!
