### ISSUE TITLE
Indenting not consistent with elm-format, even with cycling

### ISSUE THREAD

**Issue by fredcy** [jcollard/elm-mode#55]
If I write `main = div [] []` then elm-format will render it as

```elm
main =
  div
    []
    []
```

When I try to enter code that way using elm-mode I cannot get the arguments to `div` to be indented by 2 relative to it no matter how I cycle by hitting the tab key.  The closest I can get is this:

```elm
main =
  div
  []
  []
```

I'm using  elm-mode-20160104.233.

**Comment by Bogdanp** [comment]
I'll try to address this and a few other inconsistencies within the next few weeks.

**Comment by fredcy** [comment]
Thanks, that did fix the case I reported. But now I have a similar issue. The following code is as elm-format generates:

```elm
test =
  form
    [ action "foo" ]
    [ ol
        []
        [ li
            []
            [ text "foo" ]
        ]
    ]
```
I can't get elm-mode to align that line with `[ li` like that no matter how I cycle with Tab. I am using elm-mode-20160109.511 from elpa.

**Comment by Bogdanp** [comment]
Thanks for reporting! This should now be fixed. There's still some funkiness when it comes to indenting stuff like:

```elm
f = 
  ( a
  , b
  , div 
      []
      []
  )
```

That second `[]` will need cycling but it should let you cycle to the correct position.

**Comment by fredcy** [comment]
Thanks, that's now working fine for me using elm-mode 20160112.133.
