### ISSUE TITLE
Use `defcustom` where appropriate

### ISSUE THREAD

**Issue by abingham** [jcollard/elm-mode#58]
It would be nice if some of the variables in `elm-mode` were declared with `defcustom` rather than `defvar` to simplify customization. For example, I'd like to be able to customize `elm-compile-arguments` sometimes. I'd be happy to provide patches, but I wanted to see if you were interested in such changes before I went to the effort.

Also, thanks for `elm-mode`! It's great, and it's really made learning elm a joy :)

**Comment by Bogdanp** [comment]
> Also, thanks for elm-mode! It's great, and it's really made learning elm a joy :) 

Glad to hear it!

I'm interested in any patch that is likely to improve the user experience of elm-mode so please do provide 'em. :)

**Comment by abingham** [comment]
OK, I've submitted an initial patch. As I have more, I'll send them your way.
