### ISSUE TITLE
Triple-quoted strings not interpreted as single literal value

### ISSUE THREAD

**Issue by fredcy** [jcollard/elm-mode#60]
It seems that triple-quoted strings (http://elm-lang.org/docs/syntax#literals) are not handled correctly. For example, this single literal
```elm
"""foo"bar"""
```
seems to be interpreted by elm-mode as if it were these four elements (three literals and `bar` as an identifier:
```
""
"foo"
bar
""
```

**Comment by Bogdanp** [comment]
Thanks for reporting the issue! This should now be fixed.

**Comment by fredcy** [comment]
I just upgraded to elm-mode 20160211.26 and now those strings are working fine. Thank you. Elm-mode rocks.
