### ISSUE TITLE
how can I turn off elm-indent-mode?

### ISSUE THREAD

**Issue by Cifer-Y** [jcollard/elm-mode#61]
![image](https://cloud.githubusercontent.com/assets/4470516/13355798/27ebdffc-dcdd-11e5-89ee-5c3eb658fb71.png)

The indent is so strange , and I found turn off the elm-indent mode by hand is more better, so, how to turn elm-indent-mode off  automatic?

**Comment by Bogdanp** [comment]
This should work: `(add-hook 'elm-mode-hook #'turn-off-elm-indent)`

I'd suggest just learning to use the cycling for now though.
