### ISSUE TITLE
Help with Auto-Complete

### ISSUE THREAD

**Issue by hiaw** [jcollard/elm-mode#64]
I can't figure out how to get auto-complete working. I prefer auto-complete to company because the screenshot of it in action is great. I'm using spacemacs. 

I follow the instruction and added the following to .spacemacs file.

```
(add-hook 'elm-mode-hook #'elm-oracle-setup-completion)
(add-hook 'elm-mode-hook #'elm-oracle-setup-ac)
```

Then I use ```M-x auto-complete-mode```. It tells me that ```auto-complete-mode``` is enabled. But I don't get the autocomplete like you shown in the screenshot. 

I noticed when I do ```M-x auto-complete``` gives me this error.

```
Error in post-command-hook (evil-repeat-post-hook): (wrong-type-argument number-or-marker-p nil)
```

**Comment by Bogdanp** [comment]
If all you want is `auto-complete` then you don't need the first line.

Can you try running through the same steps again after calling `M-x toggle-debug-on-error RET`? I'd be interested to see the stack trace that that generates.

FWIW, Elm's auto-complete and company-mode support should be functionally equivalent even though company-mode shows you less stuff by default (function signatures are displayed in the minibuffer and you need to hit `C-h` to see documentation).

**Comment by hiaw** [comment]
Thanks for your help. I managed to get company mode working so I'll just work with that.

**Comment by radik909** [comment]
@hiaw 
This is my config for `company` and `elm`
```lisp
;;; Company
(require 'company)
(add-hook 'after-init-hook 'global-company-mode)

;;; Elm
(require 'elm-mode)
(setq elm-format-on-save t)
(setq elm-sort-imports-on-save t)
(add-hook 'elm-mode-hook #'elm-oracle-setup-completion)
(add-to-list 'company-backends 'company-elm)
```

But still autocomplete doesn't work. Help please!
