### ISSUE TITLE
Can't import file into elm-repl

### ISSUE THREAD

**Issue by dyba** [jcollard/elm-mode#65]
## What I did

I created a new elm file in emacs with elm-mode turned on:

``` elm
-- Play.elm
module Play where

import String

longestName : List String -> Maybe Int
longestName names =
  List.maximum (List.map String.length names)
```

I ran <kbd> C-c C-c </kbd> to compile the file followed by <kbd> C-c C-l </kbd> to load the file in elm-repl.

## What I expected

A new buffer running elm-repl successfully imports my file

## What I actually got

![screen shot 2016-04-13 at 8 22 47 pm](https://cloud.githubusercontent.com/assets/296219/14516275/335114b8-01b6-11e6-8a6e-6aedd24082f6.png)

Why can't the 'Play' module be found?

**Comment by Bogdanp** [comment]
What does your `elm-package.json` look like?

**Comment by dyba** [comment]
@Bogdanp It works now. I managed to find a elm.js file with an elm-stuff folder in my home directory (Note that Play.elm is not located here but in a subdirectory). I deleted both files. When I went to the subdirectory that contains the Play.elm file, I noticed there was no elm.js file nor was there an elm-stuff folder. It's possible that elm-repl was reading the elm.js file in the home directory that was stale.

Thanks for replying!

**Comment by sjt003** [comment]
still having this issue. my elm-package.json:
```{
    "version": "1.0.0",
    "summary": "helpful summary of your project, less than 80 characters",
    "repository": "https://github.com/user/project.git",
    "license": "BSD3",
    "source-directories": [
        "."
    ],
    "exposed-modules": [],
    "dependencies": {
        "elm-lang/core": "5.0.0 <= v < 6.0.0",
        "elm-lang/html": "2.0.0 <= v < 3.0.0"
    },
    "elm-version": "0.18.0 <= v < 0.19.0"
}```
