### ISSUE TITLE
Sublime like Elm-Oracle mode?

### ISSUE THREAD

**Issue by hiaw** [jcollard/elm-mode#66]
I tried out sublime today and I must say I really the way they display elm-oracle. So once turned on, it will display the entire elm-oracle output in the split window below for the word under the cursor. In this example, my cursor was on `show`.

<img width="694" alt="screenshot 2016-04-15 17 26 13" src="https://cloud.githubusercontent.com/assets/527296/14552113/30c55982-032f-11e6-8514-642e6ca87c78.png">

I know it's a big ask, but can you do this for emacs as well??

**Comment by Bogdanp** [comment]
You can look up docs using `C-c C-d` (also `C-h` during company auto completion) right now, but it won't try to guess the thing at point. I'll look into augmenting `C-c C-d` with that at some point in the coming weeks.

**Comment by Bogdanp** [comment]
You can now look up the docs for the value under the point using `C-c M-d` in addition to the `C-c C-d` functionality I mentioned before. Hope that helps!
