### ISSUE TITLE
Auto indents too far

### ISSUE THREAD

**Issue by AdamBrodzinski** [jcollard/elm-mode#73]
I'm an emacs newb so perhaps it's that but I enabled the elm layer in spacemacs and when I enter a new line the indentation doesn't line up properly. I get:

```
module Bingo where

import Html
import String

main =
  "bingo"
    |> String.toUpper
       |> String.trimRight
          |> Html.text
```

Instead of the desired result:

```
module Bingo where

import Html
import String

title =
  "bingo!"
  |> String.toUpper
  |> String.trimRight
  |> Html.text

main =
  title
```

Is there something i'm doing wrong here? Also using `ctrl =` to auto indent makes it go out of whack as well. It produces:

```
module Bingo where

  import Html
    import String
    
      title =
        "bingo!"
          |> String.toUpper
          |> String.trimRight
  |> Html.text

main =
  title
```

**Comment by Bogdanp** [comment]
Please read the README section on [indentation][indentation]. Elm has many possible indentations for most expressions and, in your case, it's assuming you want to apply some arguments to your function so it indents (a valid assumption), but the next cycle (i.e. hitting TAB once) should move the point to where you want it to be.

Auto-indent will only ever work correctly for small blocks of code (eg. within a definition) with this style of indentation.

[indentation]: https://github.com/jcollard/elm-mode#indentation

**Comment by AdamBrodzinski** [comment]
Thanks for the quick feedback @Bogdanp 

I did read the indentation section but the issue is that it's always wrong on my setup. I always have to tab because it's using 3 or 4 spaces in the screenshot below. .. perhaps it's my config (2 spaces)?

```lisp
(defun my-personal-indents (n)
  (setq indent-tabs-mode nil) ; use space instead of tab
  (setq c-basic-offset n)
  ;; web lang indents
  (setq javascript-indent-level n) ; javascript-mode
  (setq js-indent-level n) ; js-mode
  (setq js2-basic-offset n) ; js2-mode, in latest js2-mode, it's alias of js-indent-level
  (setq web-mode-markup-indent-offset n) ; web-mode, html tag in html file
  (setq web-mode-css-indent-offset n) ; web-mode, css in html file
  (setq web-mode-code-indent-offset n) ; web-mode, js code in html file
  (setq web-mode-attr-indent-offset n)
  (setq css-indent-offset n) ; css-mode
  )
```

At any rate, is there a way to disable the auto indent? It would be less work to manually indent.

**Comment by KevinGreene** [comment]
@AdamBrodzinski In case you haven't found the solution, it's described here: https://github.com/jcollard/elm-mode/issues/61

Either manually turn off `elm-indent-mode`, or use `(add-hook 'elm-mode-hook #'turn-off-elm-indent)`

**Comment by AdamBrodzinski** [comment]
Thanks @KevinGreene !
