### ISSUE TITLE
Output special chars

### ISSUE THREAD

**Issue by chalmagean** [jcollard/elm-mode#75]
How can I get rid of those special characters in my error output?

![2016-05-27 at 17 32](https://cloud.githubusercontent.com/assets/8421/15611070/439293e0-2431-11e6-8c35-4d1f6a912ea0.png)

**Comment by Bogdanp** [comment]
Most of those escape sequences (except for `^[[36m`) should be taken care of `elm-compile--colorize-compilation-buffer`. Try requiring `ansi-color` before you initialize elm-mode and make sure `elm-compile--colorize-compilation-buffer` is in your `compilation-filter-hook`s.

**Comment by chalmagean** [comment]
That doesn't seem to work. I still get those characters.

**Comment by Bogdanp** [comment]
Then you might have a different hook in `compilation-filter-hooks` (before the colorize hook) that's interfering or it could be due to something else in your setup. This seems to work fine on a vanilla Emacs install so I'm closing this issue for now.
