### ISSUE TITLE
elm-oracle + eldoc?

### ISSUE THREAD

**Issue by losingkeys** [jcollard/elm-mode#77]
The title says it all. It'd be cool to see type signatures when near/inside of functions. This code _almost_ does it:
```elisp
 (add-hook 'elm-mode-hook                                                                               
    (lambda ()                                                                                                
      (set (make-local-variable 'eldoc-documentation-function)                                           
        'elm-oracle-type-at-point)))  
```
But needs to be cleaned up:
- Avoid showing `Unknown type`. I think it's okay to just show a blank minibuffer if the type is unknown
- Show the type of the nearest function. Don't show `Unknown type` when pointing at something like `False`

**Comment by losingkeys** [comment]
Thanks for working on this! Unfortunately I'm getting some confusing results:
![nil](https://cloud.githubusercontent.com/assets/666493/18253360/bd996aca-7359-11e6-961e-30d15209815b.png)

![diff](https://cloud.githubusercontent.com/assets/666493/18253366/c6069a34-7359-11e6-9533-08b048c79dc3.png)

![string](https://cloud.githubusercontent.com/assets/666493/18253367/c98dfd8c-7359-11e6-823c-f25ee91cdafe.png)

Though it does seem to work if you're right on the function:
![intersect](https://cloud.githubusercontent.com/assets/666493/18253375/d8c60d30-7359-11e6-9155-676a1f383d31.png)

**Comment by Bogdanp** [comment]
@losingkeys I've fixed the prefixing issue, but I'm unable to reproduce the issue in your first screenshot. Can you try `M-x toggle-debug-on-error RET` and post the stack trace?

**Comment by losingkeys** [comment]
Here's the stacktrace:
```
Debugger entered--Lisp error: (void-function nil)
  nil()
  apply(nil nil)
  #[128 "\301\302\300!\"\207" [eldoc-documentation-function apply default-value] 4 "\n\n(fn &rest ARGS)"]()
  apply(#[128 "\301\302\300!\"\207" [eldoc-documentation-function apply default-value] 4 "\n\n(fn &rest ARGS)"] nil)
  #[128 "\300\301\"\206
```
The broken characters appear to be control characters. There are some `^B`s, `^K`s, `^@`s, and others. Let me know if you need them exactly.

**Comment by AlexKovalevych** [comment]
Having probably a similar issue (GNU emacs 25.1 on OSX):

```
Debugger entered--Lisp error: (void-function string-empty-p)
  string-empty-p("Array.")
  elm-oracle--function-at-point()
  elm-oracle--completion-at-point()
  elm-oracle--type-at-point()
  elm-eldoc()
  apply(elm-eldoc nil)
  #[128 "\300\301\"\206\300\302\"\207" [apply elm-eldoc #[128 "\301\302\300!\"\207" [eldoc-documentation-function apply default-value] 4 "\n\n(fn &rest ARGS)"] nil] 4 nil]()
  eldoc-print-current-symbol-info()
  #[0 "\204	\205\n\303>?\205\304 \207" [eldoc-mode global-eldoc-mode eldoc-documentation-function (nil ignore) eldoc-print-current-symbol-info] 2]()
  apply(#[0 "\204	\205\n\303>?\205\304 \207" [eldoc-mode global-eldoc-mode eldoc-documentation-function (nil ignore) eldoc-print-current-symbol-info] 2] nil)
  timer-event-handler([t 0 0 750000 t #[0 "\204	\205\n\303>?\205\304 \207" [eldoc-mode global-eldoc-mode eldoc-documentation-function (nil ignore) eldoc-print-current-symbol-info] 2] nil idle 0])

```
