### ISSUE TITLE
Support for specifying elm version for elm-format

### ISSUE THREAD

**Issue by abingham** [jcollard/elm-mode#81]
The `elm-format` command (recent versions, at least) allows you to specify the version of elm that you want to format for. It would be nice to be able to configure this for `elm-mode-format-buffer`. As things stand, the default seems to be 0.16 and this actually breaks 0.17 code when formatting is run.

**Comment by Bogdanp** [comment]
> As things stand, the default seems to be 0.16 and this actually breaks 0.17 code when formatting is run.

What version of `elm-format` are you running? `0.17` has been the default for quite some time. Either way, I've added a variable called `elm-format-elm-version`.

**Comment by abingham** [comment]
I was running elm-format 0.16. I can upgrade that, but I may still need to deal with code in different elm versions for a while, so thanks for adding the new setting.
