### ISSUE TITLE
Add "complete rebuild" command

### ISSUE THREAD

**Issue by abingham** [jcollard/elm-mode#82]
In some cases it seems that elm-make gets confused about what to build and/or doesn't recompile everything that it should. In these cases I normally nuke the elm-stuff directory and rebuild everything. It would be convenient (for me, at least) if elm-mode had a command for doing a complete rebuild like that.

**Comment by Bogdanp** [comment]
This issue is going to be fixed in 0.18 so this is a wontfix imo.

**Comment by abingham** [comment]
I agree like. Thanks for letting me know!
