### ISSUE TITLE
Multiple elm-format versions

### ISSUE THREAD

**Issue by nmk** [jcollard/elm-mode#83]
I have multiple projects running on both 0.16 and 0.17. I would like to use the appropriate elm-format on both. So I have downloaded elm-format for both versions and have them as `elm-format-0.16` and `elm-format-0.17` in my PATH.

I then tried to customise `elm-format-command` in a .dir-locals.el, like this (for the 0.17 project):

```
((nil . ((elm-format-elm-version . "0.17")
         (elm-format-command . "elm-format-0.17"))))
```

`describe-variable` after visiting a file in the project shows the correct command name has been set:

```
elm-format-command is a variable defined in ‘elm-format.el’.
Its value is "elm-format-0.17"
Local in buffer Main.elm; global value is "elm-format"

  This variable’s value is directory-local, set by the file
  ‘/Users/nmk/code/elm/test-project-0.17/.dir-locals.el’.
  This variable may be risky if used as a file-local variable.

Documentation:
The name of the ‘elm-format’ command.
```

`elm-format-buffer` seems to be using the old value though:

```
Searching for program: no such file or directory, elm-format
```

What would be the correct way to have one elm-format setting per project?

**Comment by Bogdanp** [comment]
Apologies for the late reply. Recent versions of `elm-format` take an `--elm-version` parameter that controls the source version, `elm-mode` passes `elm-format-elm-version` to that parameter so all you need to do to make this work is rename the `elm-format-0.17` to `elm-format`.
