### ISSUE TITLE
Backslash shouldn't be escape character when it's lambda

### ISSUE THREAD

**Issue by Menschenkindlein** [jcollard/elm-mode#84]
Please, make it a punctuation character or so.
Now, if you type something like `\() -> ......`, you get the bracket matching broken. And elm-format doesn't like putting space between the backslash and the argument. AFAIK, in Elm a backslash has the meaning of an escape character only in the context of strings.

**Comment by Menschenkindlein** [comment]
Thanks!
By the way, does it handle `\{records, destructuring}` correctly?

**Comment by Bogdanp** [comment]
I forgot about that case! That should now be fixed as well.

**Comment by Menschenkindlein** [comment]
Awesome!
