### ISSUE TITLE
Install with M-x package-install elm-mode fails with 404

### ISSUE THREAD

**Issue by nubunto** [jcollard/elm-mode#85]
Not sure if this is related at all to your repo, but just in case.

It errors with a 404 on address http://melpa.milkbox.net/packages/elm-mode-20161006.11.tar
Should be http://melpa.milkbox.net/packages/elm-mode-20161031.51.tar (according to manual download on melpa)

**Comment by Bogdanp** [comment]
Run `M-x package-refresh-contents RET` when this happens. This has nothing to do with `elm-mode` itself so I'm closing the issue.

**Comment by nubunto** [comment]
Oh, thank you!
