### ISSUE TITLE
Autocomplete error

### ISSUE THREAD

**Issue by hakonrossebo** [jcollard/elm-mode#89]
I've created a spacemacs issue here - https://github.com/syl20bnr/spacemacs/issues/7932
Not sure if this is related to Spacemacs or elm-mode. As described in the issue, autocomplete works as expected after using the "complete-symbol" C-M-i command.

**Comment by bmag** [comment]
FYI `make-process` was introduced in Emacs 25.1, and you're using it here: https://github.com/jcollard/elm-mode/blob/529c20acb9efda756b69e267d73d33c66fa08293/elm-interactive.el#L886

**Comment by Bogdanp** [comment]
Thanks @bmag, I didn't realize `make-process` was introduced that recently. I've made the completion function degrade gracefully (to a sync call) when `make-process` is not available. I believe that'll fix the issue.

**Comment by hakonrossebo** [comment]
Thanks - works fine now :100:

**Comment by Bogdanp** [comment]
@hakonrossebo You're welcome. I'd still suggest upgrading to 25.1 since there is a large performance difference between the sync and async completion implementations.
