### ISSUE TITLE
Incorrect operator on insert newline

### ISSUE THREAD

**Issue by chobytes** [jcollard/elm-mode#91]
When adding a newline following a sum type, elm-mode is inserting the function application operator "|>", as opposed to the type union operator "|".

Gif of the issue:
![elm](https://cloud.githubusercontent.com/assets/12215271/21324183/50c8c4a6-c5e6-11e6-9749-415495c8730d.gif)

elm-mode version 20161210.49
emacs version 25.1.50.1

**Comment by purcell** [comment]
I'm not convinced that `elm-mode` does anything other than insert a newline in this case. Are you sure you don't have other modes or settings which are influencing this behaviour? If you could provide steps to reproduce, that'd be really helpful. Start with launching emacs with `-Q`, then evaluate the following in `*scratch*`:
```el
(push "/directory/containing/elm-mode" load-path)
(require 'elm-mode)
```

**Comment by purcell** [comment]
Oh - I see this now. I'll investigate.

**Comment by purcell** [comment]
This now happens in the following case:
```elm
data Foo
   = Bar
   | Baz
#    %
```

where either:
- `%` is the cursor position and we hit newline, or
- `#` is the cursor position, and we hit newline twice.

Sadly `elm-indent.el` is almost entirely inscrutable, and it's not at all obvious how to go about fixing this properly, even though it's trivial to find the actual code which inserts `|>`.

**Comment by kRITZCREEK** [comment]
Hey, I'm maintaining PureScript's Emacs integration, and I'm also stuck with a copy of haskell-mode's indentation code. Do you think there is a less sophisticated solution that could work for both of our languages? I wouldn't mind moving some indentation around as long as the behaviour is predictable and consistent.

**Comment by purcell** [comment]
Hi @kRITZCREEK - good to know I'm not the only one experiencing a case of WAT. Not sure about Purescript, but I suspect that an overhaul of `elm-indent` would be possible using the relatively recent SMIE indentation system. Whatever the case, it's a big job to rewrite indentation code for a language, particularly a language that has variable indentation.

**Comment by kRITZCREEK** [comment]
Thanks a lot for pointing me at that. That seems like a good starting point indeed, I'll see if I can get something simple working and how well it works on PS/Elm!

**Comment by purcell** [comment]
Nice! Keep me posted. :-)

**Comment by purcell** [comment]
This is now fixed (thanks @nick96) but if you make any progress with SMIE, @kRITZCREEK, let us know!
