### ISSUE TITLE
Issues using C-c C-a to insert type annotations

### ISSUE THREAD

**Issue by Zimmi48** [jcollard/elm-mode#92]
Hi, I'm discovering elm-mode and liking it so far. I have noticed two problem when using C-c C-a to insert type annotations though.

The first problem is that the insertion only works when the current buffer was not compiled first. If I compile the buffer using C-c C-c, then C-c C-a prints "Nothing to do." but if I skip the first step and there is a compilation error while doing C-c C-a then the error is not printed.

The second problem is that depending on the cursor position, some type annotations are inserted in the middle of a function definition, thus making the buffer not compile anymore. To avoid this problem, I must move the cursor out of the function definition before doing C-c C-a.

**Comment by purcell** [comment]
> The first problem is that the insertion only works when the current buffer was not compiled first. If I compile the buffer using C-c C-c, then C-c C-a prints "Nothing to do."

This works fine for me with the current `elm-mode` and Elm 0.18.

> but if I skip the first step and there is a compilation error while doing C-c C-a then the error is not printed.

This is expected, because if there is a compilation error, then Elm cannot tell us what the type should be.

> The second problem is that depending on the cursor position, some type annotations are inserted in the middle of a function definition, thus making the buffer not compile anymore. To avoid this problem, I must move the cursor out of the function definition before doing C-c C-a.

I also can't reproduce this with the latest elm and elm-mode. Could you provide a specific example, please?

**Comment by Zimmi48** [comment]
>> The first problem is that the insertion only works when the current buffer was not compiled first. If I compile the buffer using C-c C-c, then C-c C-a prints "Nothing to do."
>
> This works fine for me with the current elm-mode and Elm 0.18.

With the latest elm-mode, I don't have this problem anymore. 

>> but if I skip the first step and there is a compilation error while doing C-c C-a then the error is not printed.
>
> This is expected, because if there is a compilation error, then Elm cannot tell us what the type should be.

Yeah, I don't mind since I can first run the compilation.

>> The second problem is that depending on the cursor position, some type annotations are inserted in the middle of a function definition, thus making the buffer not compile anymore. To avoid this problem, I must move the cursor out of the function definition before doing C-c C-a.
>
> I also can't reproduce this with the latest elm and elm-mode. Could you provide a specific example, please?

Take this program:

```elm
module Main exposing (..)


f x y =
    x + y


g x y =
    x ++ y


h x y z =
    x + y + z
```

Compile the program then do C-c C-a.
You get this:

```elm
module Main exposing (..)


f x y =
    x + y
f : number -> number -> number


g x y =
g : appendable -> appendable -> appendable
    x ++ y


h : number -> number -> number -> number
h x y z =
    x + y + z
```

The type annotations are not added where they should be. The program cannot compile anymore.
The problem doesn't appear if you add type annotations after each function you add. So I bet this is why you never experienced it.
In any case, this looks like a very stupid misalignment problem. The type annotation at the bottom is well-aligned, then there is a 1-line error for the type annotation above, then a 2-line error for the one just above, etc.

**Comment by purcell** [comment]
That final issue is fixed now: turns out the missing annotations were being applied in reverse order.

**Comment by Zimmi48** [comment]
Working great. Thanks!
