### ISSUE TITLE
Please don't bind C-c <letter>

### ISSUE THREAD

**Issue by bremner** [jcollard/elm-mode#94]
I quote the Emacs lisp reference D.2 Key Binding Conventions

>  Don’t define ‘C-c LETTER’ as a key in Lisp programs.  Sequences
>   consisting of ‘C-c’ and a letter (either upper or lower case) are
>   reserved for users; they are the *only* sequences reserved for
>    users, so do not block them.
>
>   Changing all the Emacs major modes to respect this convention was a
>    lot of work; abandoning this convention would make that work go to
>    waste, and inconvenience users.  Please comply with it.

**Comment by purcell** [comment]
I agree with this, and `elm-mode` should be a good citizen in this regard: it currently affects only `C-c t` (`elm-test-project`). I'll select another binding.

**Comment by purcell** [comment]
I went with `C-c C-v`, for the mnemonic "verify".
