### ISSUE TITLE
elm-test-project when called from Tests.elm

### ISSUE THREAD

**Issue by marshallflax** [jcollard/elm-mode#95]
If I run elm-test-project from an elm file in my main project (e.g. src/Main.elm), then it runs perfectly.  But if I run it from an elm file in my test directory (e.g. tests/Tests.elm), the working directory passed to elm-test is ./tests and so it can't find tests/Main.elm within it.  Since I frequently want to run a test just after defining it, this is less-than optimal.  Here is the typical output.  

```
-*- mode: compilation; default-directory: "~/gits/lexical/tests/" -*-
Compilation started at Sun Jan  8 22:17:23

elm-test
Could not find file tests/Main.elm

Compilation exited abnormally with code 1 at Sun Jan  8 22:17:24
```

p.s. Workaround:
```cd tests; ln -s  . tests```

**Comment by purcell** [comment]
Do you have an `elm-package.json` in your tests directory? From looking at the source for `elm-test-project`, this could be the problem. You should have a single `elm-package.json` in the root of your elm project dir.

**Comment by stubillwhite** [comment]
I ran into this issue recently, too. I tried removing the `elm-package.json` file from the `tests/` directory but that didn't work for me, and also broke elm-test on the command-line. Unless I'm misreading, the [elm-test README](https://github.com/elm-community/elm-test) suggests that elm-test requires a copy of the `elm-package.json` in the `tests/` directory to work.

I'm not sure if the fault is in my configuration/understanding, or whether the code which finds the `elm-package.json` should be tweaked to ignore the file if it exists in the `tests/` directory when running tests. I've added some advice around the function to try to do that and it seems to work fine -- I can now run tests either from within the `tests/` directory or the main `src/` directory. I can't see any ill-effects, but I haven't done much testing. 

If this is an appropriate tweak and you'd like a merge request then let me know -- I'm more than happy to help. If not, and I've completely got the wrong end of the stick here, then apologies.

```
(defun sbw/elm-mode--ignore-tests-dependency-file (orig-fun &rest args)
  (if-let ((result (apply orig-fun args)))
    (if (s-suffix? "tests/" result)
        (let ((default-directory (concat result "..")))
          (elm--find-dependency-file-path))
      result)))

(advice-add 'elm--find-dependency-file-path :around #'sbw/elm-mode--ignore-tests-dependency-file)
```

**Comment by purcell** [comment]
I've committed a fix to this in a8c76c0: let me know if you still have any issues.

**Comment by stubillwhite** [comment]
Thanks for the quick fix. That works for me now if run in either the `tests/` directory or in the root of the project, but I think there's a typo in the fix that will stop it working in subdirectories like `src/MyPackage/`. 

I might be misreading, but it looks like the lambda is referring to `default-directory` instead of `dir`, which looks like a typo to me:

    (lambda (dir)
         (and (not (s-suffix-p "/tests/" dir))
              (file-exists-p (expand-file-name elm-package-json default-directory))))

Switching that to `dir` fixes the issue for me in the root of the project, the `tests/` directory, and subdirectories of `src/`.

I completely forgot in my previous comment to say thanks for all your work on elm-mode! I really appreciate it. I'm finding elm-mode really comfortable to work in and it's made learning the language so much more pleasurable. Thanks again.

**Comment by purcell** [comment]
@stubillwhite Fixed now in ece6337, thanks!

**Comment by purcell** [comment]
I'm also really happy with `elm-mode`, and it's nice to be able to help @jcollard & co. out a little here and there. :-)

**Comment by stubillwhite** [comment]
Updated and can confirm that it's working perfectly. Thanks again! :-)
