### ISSUE TITLE
Syntax highlighting on some comments is incorrect

### ISSUE THREAD

**Issue by ajlende** [jcollard/elm-mode#99]
Single line comment highlighting overrides the multi-line commenting as seen in the screenshot below.

![screen shot 2017-03-26 01 14 17 pm](https://cloud.githubusercontent.com/assets/5129775/24333905/371768b4-1226-11e7-8aea-762df796c87c.png)

**Comment by jcollard** [comment]
I'm unable to reproduce on my system.

Which version of emacs are you using?

**Comment by ajlende** [comment]
I just installed it yesterday, so the latest version (25.1). I'm actually loading this via the Spacemacs Elm Layer, so that might have something to do with it too.

**Comment by ajlende** [comment]
Removed spacemacs configuration (`~/.emacs.d`, `~/.spacemacs`, and `~/.emacs`) and did a clean install, but the problem still persisted for me.

![screen shot 2017-03-28 06 28 59 pm](https://cloud.githubusercontent.com/assets/5129775/24432021/ffb3df40-13e4-11e7-97b7-624f059076f0.png)

**Comment by purcell** [comment]
I believe #106 fixes this.
